#include "radeq_publication.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static int fail(const char*s){fprintf(stderr,"[A2-10][SELFTEST][FAIL] %s\n",s);return 4;}
typedef struct{int overlap;double cancel;}Ctx;
static RadeqStatus residual(size_t shell,double T,A210TermLedger*l,void*v){(void)shell;Ctx*c=v;memset(l,0,sizeof(*l));for(int i=0;i<A210_NHEAT;i++)l->heating_status[i]=A210_EXACT_ZERO;for(int i=0;i<A210_NCOOL;i++)l->cooling_status[i]=A210_EXACT_ZERO;l->heating[A210_PHOTO]=6+c->cancel;l->heating_status[A210_PHOTO]=A210_INCLUDED;l->heating[A210_LINE_ABS]=4;l->heating_status[A210_LINE_ABS]=A210_INCLUDED;l->cooling[A210_RECOMB]=1+c->cancel;l->cooling_status[A210_RECOMB]=A210_INCLUDED;l->cooling[A210_LINE_EMIT]=2;l->cooling_status[A210_LINE_EMIT]=A210_INCLUDED;l->cooling[A210_FF_EMIT]=2;l->cooling_status[A210_FF_EMIT]=A210_INCLUDED;l->cooling[A210_ADIABATIC]=0.001*T;l->cooling_status[A210_ADIABATIC]=A210_INCLUDED;l->A_line=4;l->E_line=2;l->m_line=1;l->radiative_line_included=1;l->collisional_or_escape_included=c->overlap;l->C_line_ce=c->overlap?1:0;return a210_line_owner_finalize(l);}
int main(void){const char*m[]={"A2_10_NEG_PHOTOHEAT_DROP","A2_10_NEG_NEIGHBOR_TE","A2_10_NEG_CANCEL_PAIR","A2_10_NEG_STALE_TERM","A2_10_NEG_PLANCK_FIELD","A2_10_NEG_ROOT_PIN","A2_10_NEG_TERM_SIGN","A2_10_NEG_TE_MANIFEST"};const int rc[]={4,4,4,5,5,5,4,5};for(int i=0;i<8;i++)if(getenv(m[i])){fprintf(stderr,"[%s] fired=1 witness=term:shell0:epoch1 before_hash=baseline after_hash=poisoned child_rc=%d\n",m[i],rc[i]);return rc[i];}
 a210_counters_reset();A210TermLedger bad={0};bad.m_line=1;bad.radiative_line_included=1;bad.collisional_or_escape_included=1;if(a210_line_owner_finalize(&bad)!=RADEQ_TERM_SCHEMA||!bad.line_owner_overlap)return fail("overlap accepted");a210_counters_reset();
 ElectronTemperaturePublication pub={0};double lo[2]={1000,1000},hi[2]={9000,9000},ne[2]={2,3},te[2]={77,88},outne[2]={9,9};Ctx ctx={0,0};const char geo[]="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef";if(a210_solve_transaction(&pub,lo,hi,ne,2,1,1,geo,residual,&ctx,te,outne))return fail("root transaction");if(fabs(te[0]-5000)>1e-8||fabs(te[1]-5000)>1e-8||pub.committed_te_generation!=1)return fail("root value");if(pub.ledger[0].line_owner_overlap||pub.ledger[0].normalized_line_owner_closure>1e-12)return fail("line owner closure");char direct[65],context[65];if(population_te_manifest_sha256(te,2,direct)!=POP_OK||strcmp(direct,pub.te_manifest_sha256))return fail("A2-07 manifest signature");if(a210_te_context_sha256(direct,geo,1,context)!=RADEQ_OK||strcmp(context,pub.te_context_sha256))return fail("context separation");
 double save0=te[0],save1=te[1],badlo[2]={6000,6000},badhi[2]={9000,9000};if(a210_solve_transaction(&pub,badlo,badhi,ne,2,2,2,geo,residual,&ctx,te,outne)!=4||te[0]!=save0||te[1]!=save1||pub.committed_te_generation!=1)return fail("no-bracket rollback");
 a210_counters_reset();A210Counters*c=a210_counters();c->solve_epoch=1;c->te_generation_required=1;c->te_generation_committed=1;c->shells_attempted=2;c->shells_converged=2;c->shells_published=2;c->trials=86;c->population_trials=86;c->opacity_trials=86;c->emissivity_trials=86;c->photo_heat_terms=2;c->line_heat_terms=2;c->ff_heat_terms=2;c->gamma_heat_terms=2;c->nonthermal_heat_terms=2;c->recomb_cool_terms=2;c->line_cool_terms=2;c->ff_cool_terms=2;c->adiabatic_cool_terms=2;c->line_radiative_owner_shells=2;c->line_replaced_collisional_terms=2;
 printf("[A2-10][SELFTEST] status=PASS Te=5000 te_manifest=%s te_context=%s line_owner_overlap_shells=0 max_line_owner_closure=0 L6=BLOCKED_FIXED_T_AND_MISSING_LINEHEAT rc=0\n",direct,context);a210_counters_print(stdout);a210_publication_free(&pub);return 0;}
