#!/bin/bash
# THEN_MC segfault bisect: run a 2-iter pure-CMFGEN + THEN_MC pass with binary $1.
# Prints PASS if the MC pass survives 60s past the THEN-MC banner, CRASH on segv.
BIN=${1:?binary}
cd /home/kjhan/BACKUP/Eunha.A1/Claude/Lumina-sn
module load cuda/13.0.2 2>/dev/null
export OMP_NUM_THREADS=60 OMP_PLACES=cores OMP_PROC_BIND=close LUMINA_CMF_SOLVE_GPU=1 CUDA_VISIBLE_DEVICES=0
MODEL=data/tardis_reference_toy06_19p48d
set -a
LUMINA_NLTE=1 LUMINA_NLTE_GREY_ITERS=2 SUPER_LEVELS=1 LUMINA_NLTE_GREY_TAU=2
LUMINA_MACROATOM_NEUTRAL_E=1 LUMINA_SUPER_CUTOFF=100 LUMINA_GAMMA_DEP=1
LUMINA_NLTE_ASSEMBLE_GPU=1 LUMINA_DEPOSITION_FILE=$MODEL/deposition_cmfgen.csv
LUMINA_PURE_CMFGEN=1 LUMINA_PURE_CMFGEN_ITER=2 LUMINA_CMFGEN_ALI_ITER=8
LUMINA_BF_OPACITY=1 LUMINA_CMFGEN_SIGMA_BF=$MODEL/cmfgen_sigma_bf.bin
LUMINA_DYNAMIC_TRANSPROB=1 LUMINA_NLTE_SKIP_Z=14 LUMINA_NLTE_START_ITER=2
LUMINA_NLTE_FLOOR_REG=0 LUMINA_NLTE_INV_CEIL=1e4 LUMINA_RADEQ_TE=1
LUMINA_RADEQ_COOL_ESCAPE=0 LUMINA_RADEQ_COOL_NONNEG=0 LUMINA_RADEQ_COOL_NLTE_ONLY=0
LUMINA_RADEQ_LINE_RESPOND=1 LUMINA_RADEQ_DAMP=0.5 LUMINA_COUPLED_NEWTON=0
LUMINA_CN_DAMP=0.5 LUMINA_COUPLED_NEWTON_SMIN=20 LUMINA_COUPLED_JNU_PHOTOION=1
LUMINA_FROZENIN=0 LUMINA_NLTE_PER_ION_RESCALE=1 LUMINA_COUPLED_JNU_LSTAR=0
LUMINA_COUPLED_LAMBDA_STAR=1 LUMINA_COUPLED_TDEP=1 LUMINA_RADEQ_LINE_RE=0
LUMINA_TE_TRAD_RATIO=1.0 LUMINA_LINE_INTERACTION=macroatom LUMINA_TAU_BY_ION=1
LUMINA_DIFFUSE_INNER_BC=1 LUMINA_ENERGY_BUDGET=1 LUMINA_NLTE_LTE_FLOOR=1
LUMINA_NLTE_COLL_FIX=1 LUMINA_NLTE_ION_LOCK=1 LUMINA_NLTE_LOCK_START_ITER=0
LUMINA_NLTE_FALLBACK_TE=1 LUMINA_CMFGEN_FROZEN_CONT=1 LUMINA_CMFGEN_FROZEN_ALI=60
LUMINA_MACROATOM_EWEIGHT=1 LUMINA_CMFGEN_LINE_EPS_PHYS=1
LUMINA_STAGE0_DIAG=1 LUMINA_RADEQ_DIAG=1 LUMINA_CN_RTRUTH=1 LUMINA_COUPLED_NT=1
LUMINA_FROZENIN_DR=1 LUMINA_TDEP_EQIC=1 LUMINA_RADEQ_FB_RATE=1 LUMINA_HRESP_CLAMP=1.0
LUMINA_TE_STEP_CLAMP=1 LUMINA_BF_RATE_POPS=1 LUMINA_ETLA_ALLOW_HEAT=1
LUMINA_RADEQ_SIMUL=1 LUMINA_TRAD_COLOR_FIX=1 LUMINA_J_DAMP=0.5 LUMINA_RADEQ_VR_STD=1
LUMINA_INNER_BB_SCALE=1.0 LUMINA_CMF_DEP_SOURCE=1 LUMINA_CMFGEN_THEN_MC=1
LUMINA_CMF_EPAY=2 LUMINA_CMF_EPAY_SMIN=5 LUMINA_CMF_BF_MILNE=2 LUMINA_CMF_EPAY_HOTF=0
LUMINA_MAX_INTERACTIONS=${MAXI:-1000}
set +a
OUT=/tmp/claude-10396/-home-kjhan-BACKUP-Eunha-A1-Claude-Lumina-sn/f5549e0b-f5d0-4d4a-8024-0bb561d5a21d/scratchpad/bisect_$(basename $BIN).log
timeout 900 ./$BIN "$MODEL" 20000 3 spectrum nlte > "$OUT" 2>&1
rc=$?
if grep -q "THEN-MC" "$OUT"; then
  if [ $rc -eq 139 ]; then echo "$BIN: CRASH (segv after THEN-MC banner)";
  elif [ $rc -eq 124 ]; then echo "$BIN: PASS-ish (still running at timeout past banner)";
  else echo "$BIN: rc=$rc $(tail -1 $OUT | head -c 80)"; fi
else
  echo "$BIN: rc=$rc did not reach THEN-MC ($(tail -1 $OUT | head -c 80))"
fi
