/* Offline-only A2-17 converter. This TU is intentionally absent from every
 * production link line. It is the sole parser of legacy W/T_rad columns. */
#include "jnu_seed.h"

#include <errno.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define H_PLANCK_SEED 6.62607015e-27
#define K_BOLTZMANN_SEED 1.380649e-16
#define C_LIGHT_SEED 2.99792458e10

typedef struct { uint64_t id; double dilution; double color_temperature; } LegacyRow;
typedef struct { uint64_t id; double lower; double upper; } ShellRow;

static int column(char *header,const char *name){int i=0;for(char*p=strtok(header,",\r\n");p;p=strtok(NULL,",\r\n"),i++)if(!strcmp(p,name))return i;return-1;}
static int fields(char *line,char **v,int cap){int n=0;for(char*p=strtok(line,",\r\n");p&&n<cap;p=strtok(NULL,",\r\n"))v[n++]=p;return n;}
static int read_legacy(const char*path,LegacyRow**out,size_t*n){FILE*f=fopen(path,"r");if(!f)return-1;char line[4096],copy[4096];if(!fgets(line,sizeof(line),f)){fclose(f);return-1;}strcpy(copy,line);int ci=column(copy,"shell_id");strcpy(copy,line);int cw=column(copy,"W");strcpy(copy,line);int ct=column(copy,"T_rad");if(cw<0||ct<0){fclose(f);return-1;}size_t z=0,cap=64;LegacyRow*a=malloc(cap*sizeof(*a));while(fgets(line,sizeof(line),f)){char*v[64];int nf=fields(line,v,64);if(cw>=nf||ct>=nf||(ci>=0&&ci>=nf)){free(a);fclose(f);return-1;}if(z==cap){cap*=2;LegacyRow*t=realloc(a,cap*sizeof(*a));if(!t){free(a);fclose(f);return-1;}a=t;}char*e=NULL;errno=0;a[z].id=ci>=0?strtoull(v[ci],&e,10):(uint64_t)z;if(errno||!e||*e){free(a);fclose(f);return-1;}a[z].dilution=strtod(v[cw],&e);if(!e||*e||!isfinite(a[z].dilution)||a[z].dilution<0.0){free(a);fclose(f);return-1;}a[z].color_temperature=strtod(v[ct],&e);if(!e||*e||!isfinite(a[z].color_temperature)||a[z].color_temperature<=0.0){free(a);fclose(f);return-1;}z++;}fclose(f);*out=a;*n=z;return z?0:-1;}
static int read_geometry(const char*path,ShellRow**out,size_t*n){FILE*f=fopen(path,"r");if(!f)return-1;char line[4096],copy[4096];if(!fgets(line,sizeof(line),f)){fclose(f);return-1;}strcpy(copy,line);int ci=column(copy,"shell_id");strcpy(copy,line);int cl=column(copy,"v_inner");strcpy(copy,line);int cu=column(copy,"v_outer");if(cl<0||cu<0){fclose(f);return-1;}size_t z=0,cap=64;ShellRow*a=malloc(cap*sizeof(*a));while(fgets(line,sizeof(line),f)){char*v[64],*e=NULL;int nf=fields(line,v,64);if(cl>=nf||cu>=nf||(ci>=0&&ci>=nf)){free(a);fclose(f);return-1;}if(z==cap){cap*=2;ShellRow*t=realloc(a,cap*sizeof(*a));if(!t){free(a);fclose(f);return-1;}a=t;}a[z].id=ci>=0?strtoull(v[ci],&e,10):(uint64_t)z;if(!e||*e){free(a);fclose(f);return-1;}a[z].lower=strtod(v[cl],&e);if(!e||*e){free(a);fclose(f);return-1;}a[z].upper=strtod(v[cu],&e);if(!e||*e||!isfinite(a[z].lower)||!isfinite(a[z].upper)||a[z].lower>=a[z].upper||(z&&a[z].lower!=a[z-1].upper)){free(a);fclose(f);return-1;}z++;}fclose(f);*out=a;*n=z;return z?0:-1;}
static double bnu(double nu,double t){double x=H_PLANCK_SEED*nu/(K_BOLTZMANN_SEED*t);if(x>745.0)return 0.0;return(2.0*H_PLANCK_SEED*nu*nu*nu/(C_LIGHT_SEED*C_LIGHT_SEED))/expm1(x);}
static double average(double lo,double hi,double t){static const double x[8]={0.09501250983763744,0.2816035507792589,0.4580167776572274,0.6178762444026438,0.7554044083550030,0.8656312023878318,0.9445750230732326,0.9894009349916499};static const double w[8]={0.1894506104550685,0.1826034150449236,0.1691565193950025,0.1495959888165767,0.1246289712555339,0.0951585116824928,0.0622535239386479,0.0271524594117541};double m=.5*(lo+hi),h=.5*(hi-lo),sum=0.0;for(int i=0;i<8;i++)sum+=w[i]*(bnu(m-h*x[i],t)+bnu(m+h*x[i],t));return .5*sum;}
static int wr(FILE*f,const void*p,size_t z,size_t n){return fwrite(p,z,n,f)==n?0:-1;}
int main(int argc,char**argv){if(argc!=5){fprintf(stderr,"usage: %s plasma_state.csv geometry.csv output.jnu_seed epoch_s\n",argv[0]);return 2;}char*e=NULL;double epoch=strtod(argv[4],&e);if(!e||*e||!isfinite(epoch)||epoch<=0.0)return 2;LegacyRow*l=NULL;ShellRow*g=NULL;size_t nl=0,ng=0;if(read_legacy(argv[1],&l,&nl)||read_geometry(argv[2],&g,&ng)||nl!=ng){free(l);free(g);fprintf(stderr,"A2_17_LEGACY_CONVERTER_SCHEMA_FAIL\n");return 2;}for(size_t s=0;s<nl;s++)if(l[s].id!=g[s].id){free(l);free(g);return 2;}char ph[65],gh[65];if(jnu_seed_sha256_file(argv[1],ph)||jnu_seed_sha256_file(argv[2],gh)){free(l);free(g);return 2;}size_t nb=LUMINA_RADFIELD_N_BINS,cells=nl*nb;double*edges=malloc((nb+1)*sizeof(*edges)),*j=malloc(cells*sizeof(*j));unsigned char*v=malloc(cells);uint64_t*ids=malloc(nl*sizeof(*ids));double*shell=malloc((nl+1)*sizeof(*shell));if(!edges||!j||!v||!ids||!shell){free(l);free(g);free(edges);free(j);free(v);free(ids);free(shell);return 2;}double dl=log(LUMINA_RADFIELD_NU_MAX_HZ/LUMINA_RADFIELD_NU_MIN_HZ)/(double)nb;for(size_t b=0;b<=nb;b++)edges[b]=LUMINA_RADFIELD_NU_MIN_HZ*exp((double)b*dl);edges[0]=LUMINA_RADFIELD_NU_MIN_HZ;edges[nb]=LUMINA_RADFIELD_NU_MAX_HZ;for(size_t s=0;s<nl;s++){ids[s]=g[s].id;shell[s]=g[s].lower;for(size_t b=0;b<nb;b++){size_t q=s*nb+b;j[q]=l[s].dilution*average(edges[b],edges[b+1],l[s].color_temperature);v[q]=(unsigned char)RADIATION_FIELD_VALID;}}shell[nl]=g[nl-1].upper;
 JnuSeedDiskHeader h;memset(&h,0,sizeof(h));memcpy(h.magic,LUMINA_JNU_SEED_MAGIC,16);h.version=LUMINA_JNU_SEED_VERSION;h.endian_tag=0x01020304U;h.n_shells=nl;h.n_bins=nb;h.units=RADIATION_FIELD_UNITS_ERG_S_NEG1_CM_NEG2_HZ_NEG1_SR_NEG1;h.frame=RADIATION_FIELD_FRAME_SHELL_COMOVING;h.provenance=RADIATION_FIELD_PROVENANCE_DILUTE_PLANCK_LEGACY_APPROXIMATION;h.epoch=epoch;memcpy(h.shape_sha256,LUMINA_JNU_SEED_SHAPE_SHA256,65);memcpy(h.edge_sha256,LUMINA_RADFIELD_EDGE_SHA256,65);memcpy(h.source_payload_sha256,ph,65);memcpy(h.source_geometry_sha256,gh,65);
 FILE*f=fopen(argv[3],"wb");int bad=!f||wr(f,&h,sizeof(h),1)||wr(f,ids,sizeof(*ids),nl)||wr(f,shell,sizeof(*shell),nl+1)||wr(f,edges,sizeof(*edges),nb+1)||wr(f,v,1,cells)||wr(f,j,sizeof(*j),cells);if(f&&fclose(f))bad=1;free(l);free(g);free(edges);free(j);free(v);free(ids);free(shell);if(bad)return 2;printf("A2_17_LEGACY_CONVERTER_PASS rows=%zu bins=%zu cells=%zu provenance=DILUTE_PLANCK_LEGACY_APPROXIMATION\n",nl,nb,cells);return 0;}
