#include "emissivity_publication.h"

#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

typedef struct { uint32_t h[8]; uint64_t bits; unsigned char b[64]; size_t used; } A209Sha;
static A209Counters g_ctr;
static uint32_t rr(uint32_t x,unsigned n){return(x>>n)|(x<<(32U-n));}
static void sha_block(A209Sha*s,const unsigned char*b){
 static const uint32_t k[64]={0x428a2f98U,0x71374491U,0xb5c0fbcfU,0xe9b5dba5U,0x3956c25bU,0x59f111f1U,0x923f82a4U,0xab1c5ed5U,0xd807aa98U,0x12835b01U,0x243185beU,0x550c7dc3U,0x72be5d74U,0x80deb1feU,0x9bdc06a7U,0xc19bf174U,0xe49b69c1U,0xefbe4786U,0x0fc19dc6U,0x240ca1ccU,0x2de92c6fU,0x4a7484aaU,0x5cb0a9dcU,0x76f988daU,0x983e5152U,0xa831c66dU,0xb00327c8U,0xbf597fc7U,0xc6e00bf3U,0xd5a79147U,0x06ca6351U,0x14292967U,0x27b70a85U,0x2e1b2138U,0x4d2c6dfcU,0x53380d13U,0x650a7354U,0x766a0abbU,0x81c2c92eU,0x92722c85U,0xa2bfe8a1U,0xa81a664bU,0xc24b8b70U,0xc76c51a3U,0xd192e819U,0xd6990624U,0xf40e3585U,0x106aa070U,0x19a4c116U,0x1e376c08U,0x2748774cU,0x34b0bcb5U,0x391c0cb3U,0x4ed8aa4aU,0x5b9cca4fU,0x682e6ff3U,0x748f82eeU,0x78a5636fU,0x84c87814U,0x8cc70208U,0x90befffaU,0xa4506cebU,0xbef9a3f7U,0xc67178f2U};
 uint32_t w[64];for(int i=0;i<16;i++)w[i]=((uint32_t)b[4*i]<<24)|((uint32_t)b[4*i+1]<<16)|((uint32_t)b[4*i+2]<<8)|b[4*i+3];for(int i=16;i<64;i++){uint32_t x=w[i-15],y=w[i-2];w[i]=w[i-16]+(rr(x,7)^rr(x,18)^(x>>3))+w[i-7]+(rr(y,17)^rr(y,19)^(y>>10));}uint32_t a=s->h[0],c=s->h[2],d=s->h[3],e=s->h[4],f=s->h[5],g=s->h[6],h=s->h[7],bb=s->h[1];for(int i=0;i<64;i++){uint32_t t1=h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^(~e&g))+k[i]+w[i],t2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&bb)^(a&c)^(bb&c));h=g;g=f;f=e;e=d+t1;d=c;c=bb;bb=a;a=t1+t2;}s->h[0]+=a;s->h[1]+=bb;s->h[2]+=c;s->h[3]+=d;s->h[4]+=e;s->h[5]+=f;s->h[6]+=g;s->h[7]+=h;
}
static void sha_init(A209Sha*s){uint32_t h[8]={0x6a09e667U,0xbb67ae85U,0x3c6ef372U,0xa54ff53aU,0x510e527fU,0x9b05688cU,0x1f83d9abU,0x5be0cd19U};memcpy(s->h,h,sizeof(h));s->bits=0;s->used=0;}
static void sha_up(A209Sha*s,const void*v,size_t n){const unsigned char*p=v;s->bits+=(uint64_t)n*8;while(n){size_t z=64-s->used,t=n<z?n:z;memcpy(s->b+s->used,p,t);s->used+=t;p+=t;n-=t;if(s->used==64){sha_block(s,s->b);s->used=0;}}}
static void sha_u64(A209Sha*s,uint64_t x){unsigned char b[8];for(int i=0;i<8;i++)b[7-i]=(unsigned char)(x>>(8*i));sha_up(s,b,8);}
static void sha_f64(A209Sha*s,double x){uint64_t u;memcpy(&u,&x,8);sha_u64(s,u);}
static void sha_done(A209Sha*s,char out[65]){uint64_t bits=s->bits;unsigned char x=0x80,z=0,l[8],d[32];sha_up(s,&x,1);while(s->used!=56)sha_up(s,&z,1);for(int i=0;i<8;i++)l[7-i]=(unsigned char)(bits>>(8*i));sha_up(s,l,8);for(int i=0;i<8;i++){d[4*i]=s->h[i]>>24;d[4*i+1]=s->h[i]>>16;d[4*i+2]=s->h[i]>>8;d[4*i+3]=s->h[i];}static const char h[]="0123456789abcdef";for(int i=0;i<32;i++){out[2*i]=h[d[i]>>4];out[2*i+1]=h[d[i]&15];}out[64]=0;}
static void *za(size_t n,size_t w){return n?calloc(n,w):NULL;}
static int good(EmissivityStatus s){return s==EMISS_OK||s==EMISS_EXACT_ZERO;}
static double kadd(double sum,double x,double*c){double y=x-*c,t=sum+y;*c=(t-sum)-y;return t;}

int a209_publication_init(CpuEmissivityPublication*p,size_t ns,size_t nb){if(!p||!ns||!nb)return-1;memset(p,0,sizeof(*p));p->n_shells=ns;p->n_bins=nb;size_t n=ns*nb;p->nu_edge=za(nb+1,sizeof(double));p->eta_bb=za(n,sizeof(double));p->eta_bf=za(n,sizeof(double));p->eta_ff=za(n,sizeof(double));p->eta_true_total=za(n,sizeof(double));p->eta_scattering_source=za(n,sizeof(double));p->eta_total_for_declared_semantics=za(n,sizeof(double));p->eta_reemit=za(n,sizeof(double));p->reemit_cdf=za(n,sizeof(double));p->cell_status=za(n,sizeof(*p->cell_status));p->component_status=za(5*n,sizeof(*p->component_status));if(!p->nu_edge||!p->eta_bb||!p->eta_bf||!p->eta_ff||!p->eta_true_total||!p->eta_scattering_source||!p->eta_total_for_declared_semantics||!p->eta_reemit||!p->reemit_cdf||!p->cell_status||!p->component_status){a209_publication_free(p);return-1;}return 0;}
void a209_publication_free(CpuEmissivityPublication*p){if(!p)return;free(p->nu_edge);free(p->eta_bb);free(p->eta_bf);free(p->eta_ff);free(p->eta_true_total);free(p->eta_scattering_source);free(p->eta_total_for_declared_semantics);free(p->eta_reemit);free(p->reemit_cdf);free(p->cell_status);free(p->component_status);memset(p,0,sizeof(*p));}
double a209_publication_max_closure(const CpuEmissivityPublication*p,size_t*wi){if(!p)return INFINITY;double worst=0;size_t at=0,n=p->n_shells*p->n_bins;for(size_t i=0;i<n;i++){double c=0,s=0;s=kadd(s,p->eta_bb[i],&c);s=kadd(s,p->eta_bf[i],&c);s=kadd(s,p->eta_ff[i],&c);s+=c;double all=s+p->eta_scattering_source[i],scale=fmax(fabs(p->eta_bb[i])+fabs(p->eta_bf[i])+fabs(p->eta_ff[i])+fabs(p->eta_scattering_source[i]),DBL_MIN);double e=fmax(fabs(p->eta_true_total[i]-s),fabs(p->eta_total_for_declared_semantics[i]-all))/scale;if(e>worst){worst=e;at=i;}}if(wi)*wi=at;return worst;}
int a209_build_reemit_cdf(CpuEmissivityPublication*p,unsigned mask){if(!p||!p->required_emissivity_generation){g_ctr.cdf_stale++;return 5;}g_ctr.cdf_attempted+=p->n_shells;size_t nb=p->n_bins;for(size_t s=0;s<p->n_shells;s++){double sum=0,c=0;for(size_t b=0;b<nb;b++){size_t i=s*nb+b;if(!good(p->cell_status[i])||!isfinite(p->eta_true_total[i])||p->eta_true_total[i]<0){g_ctr.cdf_invalid++;p->redistribution_status=EMISS_CDF_INVALID;return 5;}p->eta_reemit[i]=p->eta_true_total[i];double w=p->eta_reemit[i]*(p->nu_edge[b+1]-p->nu_edge[b]);sum=kadd(sum,w,&c);p->reemit_cdf[i]=sum;}sum+=c;if(!(sum>0)||!isfinite(sum)){g_ctr.cdf_empty++;p->redistribution_status=EMISS_CDF_EMPTY;return 5;}double prev=0;for(size_t b=0;b<nb;b++){size_t i=s*nb+b;double v=(b+1==nb)?1.0:p->reemit_cdf[i]/sum;if(!isfinite(v)||v<prev){g_ctr.cdf_invalid++;p->redistribution_status=EMISS_CDF_INVALID;return 5;}p->reemit_cdf[i]=v;prev=v;}}
 A209Sha h;sha_init(&h);const char d[]="A2-09:eta-reemit-cdf:v1";sha_up(&h,d,sizeof(d)-1);sha_u64(&h,p->required_emissivity_generation);sha_u64(&h,p->n_shells);sha_u64(&h,p->n_bins);sha_u64(&h,mask);for(size_t b=0;b<=p->n_bins;b++)sha_f64(&h,p->nu_edge[b]);for(size_t i=0;i<p->n_shells*p->n_bins;i++)sha_f64(&h,p->eta_reemit[i]);sha_done(&h,p->cdf_manifest_sha256);p->cdf_generation=p->required_emissivity_generation;p->channel_mask=mask;p->redistribution_status=EMISS_OK;g_ctr.cdf_committed+=p->n_shells;return 0;}
int a209_publication_commit(CpuEmissivityPublication*pub,CpuEmissivityPublication*c){if(!pub||!c||!c->required_emissivity_generation||c->committed_emissivity_generation){g_ctr.partial_publish_attempts++;return 5;}size_t n=c->n_shells*c->n_bins;for(size_t i=0;i<n;i++){if(!good(c->cell_status[i])){g_ctr.partial_publish_attempts++;return 5;}for(size_t k=0;k<5;k++)if(!good(c->component_status[k*n+i])){g_ctr.partial_publish_attempts++;return 5;}}if(a209_publication_max_closure(c,NULL)>1e-10||c->redistribution_status!=EMISS_OK||c->cdf_generation!=c->required_emissivity_generation){g_ctr.partial_publish_attempts++;return 5;}c->committed_emissivity_generation=c->required_emissivity_generation;CpuEmissivityPublication old=*pub;*pub=*c;memset(c,0,sizeof(*c));a209_publication_free(&old);g_ctr.generation_committed=pub->committed_emissivity_generation;return 0;}
int a209_sample_reemit_frequency(const CpuEmissivityPublication*p,size_t s,uint64_t gen,double u,double*nu){g_ctr.sampler_calls++;if(!p||!nu||s>=p->n_shells||p->committed_emissivity_generation!=gen||p->cdf_generation!=gen||p->redistribution_status!=EMISS_OK){g_ctr.sampler_generation_mismatch++;return 5;}if(!isfinite(u)||u<0||u>=1){g_ctr.cdf_invalid++;return 5;}g_ctr.sampler_draws++;size_t lo=0,hi=p->n_bins-1;const double*cdf=p->reemit_cdf+s*p->n_bins;while(lo<hi){size_t m=(lo+hi)/2;if(cdf[m]<u)lo=m+1;else hi=m;}double c0=lo?cdf[lo-1]:0,c1=cdf[lo],f=(c1>c0)?(u-c0)/(c1-c0):0;*nu=p->nu_edge[lo]+f*(p->nu_edge[lo+1]-p->nu_edge[lo]);return(isfinite(*nu)&&*nu>0)?0:5;}
EmissivityStatus a209_transition_block(const double*w,const double*e,size_t n,double in,double*p,double*err){g_ctr.transition_blocks_attempted++;if(!w||!p||!n){g_ctr.transition_empty++;return EMISS_TRANSITION_EMPTY;}double sum=0,c=0,es=0,ec=0;for(size_t i=0;i<n;i++){if(!isfinite(w[i])||w[i]<0|| (e&&(!isfinite(e[i])||e[i]<0))){g_ctr.transition_nonfinite++;return EMISS_TRANSITION_NONFINITE;}sum=kadd(sum,w[i],&c);}sum+=c;if(!(sum>0)||!isfinite(sum)){g_ctr.transition_empty++;return EMISS_TRANSITION_EMPTY;}double ps=0,pc=0;for(size_t i=0;i<n;i++){p[i]=w[i]/sum;ps=kadd(ps,p[i],&pc);if(e)es=kadd(es,p[i]*e[i],&ec);}ps+=pc;if(fabs(ps-1)>1e-10){g_ctr.transition_norm_fail++;return EMISS_TRANSITION_NOT_NORMALIZED;}double ne=0;if(e){es+=ec;double scale=fmax(fabs(in),DBL_MIN);ne=fabs(es-in)/scale;if(ne>1e-8){g_ctr.energy_closure_fail++;if(err)*err=ne;return EMISS_ENERGY_NOT_CLOSED;}}if(err)*err=ne;g_ctr.transition_blocks_published++;g_ctr.transition_channels+=n;return EMISS_OK;}
const char*a209_status_name(EmissivityStatus s){static const char*n[]={"INVALID","EMISS_OK","EMISS_EXACT_ZERO","EMISS_STALE_RF","EMISS_STALE_LINE","EMISS_STALE_POP","EMISS_STALE_OPACITY","EMISS_UNSAMPLED","EMISS_OOG","EMISS_MISS","EMISS_PROFILE_MISMATCH","EMISS_QUERY_HASH_MISMATCH","EMISS_INVALID_TE","EMISS_INVALID_NE","EMISS_ATOMIC_MISSING","EMISS_SOURCE_UNDEFINED","EMISS_COMPONENT_INCOMPLETE","EMISS_NEGATIVE_EVENT_UNSUPPORTED","EMISS_TRANSITION_EMPTY","EMISS_TRANSITION_NONFINITE","EMISS_TRANSITION_NOT_NORMALIZED","EMISS_ENERGY_NOT_CLOSED","EMISS_CDF_EMPTY","EMISS_CDF_STALE","EMISS_CDF_INVALID","EMISS_FORBIDDEN_PLANCK","EMISS_PARTIAL_PUBLISH","EMISS_NONFINITE"};return s>=EMISS_OK&&s<=EMISS_NONFINITE?n[s]:n[0];}
A209Counters*a209_counters(void){return &g_ctr;}void a209_counters_reset(void){memset(&g_ctr,0,sizeof(g_ctr));}
void a209_counters_print(FILE*f){if(!f)f=stdout;fprintf(f,"[A2-09][EMISSIVITY] generation_required=%llu generation_committed=%llu shells_attempted=%llu shells_published=%llu cells_attempted=%llu cells_published=%llu bb_terms=%llu bf_terms=%llu ff_terms=%llu exact_zero_terms=%llu transition_blocks_attempted=%llu transition_blocks_published=%llu transition_channels=%llu transition_empty=%llu transition_nonfinite=%llu transition_norm_fail=%llu energy_closure_fail=%llu cdf_attempted=%llu cdf_committed=%llu cdf_empty=%llu cdf_stale=%llu cdf_invalid=%llu sampler_calls=%llu sampler_draws=%llu sampler_generation_mismatch=%llu blocked_stale_rf=%llu blocked_stale_line=%llu blocked_stale_pop=%llu blocked_stale_opacity=%llu blocked_unsampled=%llu blocked_oog=%llu blocked_miss=%llu blocked_source=%llu blocked_atomic=%llu fallback_attempts=%llu planck_attempts=%llu raw_view_attempts=%llu clamp_attempts=%llu floor_attempts=%llu last_channel_attempts=%llu partial_publish_attempts=%llu nonfinite_failures=%llu\n",(unsigned long long)g_ctr.generation_required,(unsigned long long)g_ctr.generation_committed,(unsigned long long)g_ctr.shells_attempted,(unsigned long long)g_ctr.shells_published,(unsigned long long)g_ctr.cells_attempted,(unsigned long long)g_ctr.cells_published,(unsigned long long)g_ctr.bb_terms,(unsigned long long)g_ctr.bf_terms,(unsigned long long)g_ctr.ff_terms,(unsigned long long)g_ctr.exact_zero_terms,(unsigned long long)g_ctr.transition_blocks_attempted,(unsigned long long)g_ctr.transition_blocks_published,(unsigned long long)g_ctr.transition_channels,(unsigned long long)g_ctr.transition_empty,(unsigned long long)g_ctr.transition_nonfinite,(unsigned long long)g_ctr.transition_norm_fail,(unsigned long long)g_ctr.energy_closure_fail,(unsigned long long)g_ctr.cdf_attempted,(unsigned long long)g_ctr.cdf_committed,(unsigned long long)g_ctr.cdf_empty,(unsigned long long)g_ctr.cdf_stale,(unsigned long long)g_ctr.cdf_invalid,(unsigned long long)g_ctr.sampler_calls,(unsigned long long)g_ctr.sampler_draws,(unsigned long long)g_ctr.sampler_generation_mismatch,(unsigned long long)g_ctr.blocked_stale_rf,(unsigned long long)g_ctr.blocked_stale_line,(unsigned long long)g_ctr.blocked_stale_pop,(unsigned long long)g_ctr.blocked_stale_opacity,(unsigned long long)g_ctr.blocked_unsampled,(unsigned long long)g_ctr.blocked_oog,(unsigned long long)g_ctr.blocked_miss,(unsigned long long)g_ctr.blocked_source,(unsigned long long)g_ctr.blocked_atomic,(unsigned long long)g_ctr.fallback_attempts,(unsigned long long)g_ctr.planck_attempts,(unsigned long long)g_ctr.raw_view_attempts,(unsigned long long)g_ctr.clamp_attempts,(unsigned long long)g_ctr.floor_attempts,(unsigned long long)g_ctr.last_channel_attempts,(unsigned long long)g_ctr.partial_publish_attempts,(unsigned long long)g_ctr.nonfinite_failures);}
